name = "nostal-optimization"
author = "Nostal Yuu"
version = "1.6.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cbb148d36c0ba0c3990f5cd475a595b7889f11beebcc02314b19fef7a91f1cba"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"

[options]
acceptable-game-versions = ["1.21.11"]
