name = "nostal-optimization"
author = "Nostal Yuu"
version = "1.7.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5f60de2b74b6f62927e65fe06bb93507f2ec0b1846155dce47aa0f67ce6624e2"

[versions]
fabric = "0.19.2"
minecraft = "26.1"

[options]
acceptable-game-versions = ["26.1"]
