name = "nostal-optimization"
author = "Nostal Yuu"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b90dec9be449fd78801ee23703771f40d4ba86a6891660df0cc6d2e4e6b2d82f"

[versions]
minecraft = "1.20.1"
quilt = "0.19.2"
