name = "Nostal's Optimization Pack"
author = "NostalFinals"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c53c4e60e07b7c65028ee97155c0234d5627b02906d2a0b6880d0f8cff66162f"

[versions]
minecraft = "1.20.1"
quilt = "0.19.2"
