#Fabrishot screenshot config
#Wed Feb 04 21:52:11 HKT 2026
custom_file_name=huge_%time%
delay=3
file_format=PNG
height=2160
hide_hud=true
override_screenshot_key=false
save_file=true
width=3840
