#This file stores configuration options for Iris, such as the currently active shaderpack
#Sat Feb 14 13:56:46 HKT 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=32
shaderPack=ComplementaryReimagined_r5.7.1.zip
